"""parents governance m7

Revision ID: 1a2576ed05d2
Revises: 179c6a6fe678
Create Date: 2026-09-16 03:10:26.220767+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import pgvector  # noqa: F401  向量列（pgvector）迁移需要
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1a2576ed05d2'
down_revision: str | None = '179c6a6fe678'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """升级。"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=48), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('target_url', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('response_code', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alert_records'))
    )
    op.create_index(op.f('ix_alert_records_kind'), 'alert_records', ['kind'], unique=False)
    op.create_table('experiments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('variants', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metric', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_experiments'))
    )
    op.create_index(op.f('ix_experiments_key'), 'experiments', ['key'], unique=True)
    op.create_table('inspection_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_date', sa.Date(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('flagged_count', sa.Integer(), nullable=False),
    sa.Column('wrong_rate', sa.Float(), nullable=False),
    sa.Column('sympy_checked', sa.Integer(), nullable=False),
    sa.Column('sympy_passed', sa.Integer(), nullable=False),
    sa.Column('redline_hits', sa.Integer(), nullable=False),
    sa.Column('alerted', sa.Boolean(), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inspection_reports'))
    )
    op.create_index(op.f('ix_inspection_reports_run_date'), 'inspection_reports', ['run_date'], unique=False)
    op.create_table('experiment_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('experiment_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('variant', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], name=op.f('fk_experiment_assignments_experiment_id_experiments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_experiment_assignments_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_experiment_assignments')),
    sa.UniqueConstraint('experiment_id', 'user_id', name='uq_experiment_assignments')
    )
    op.create_index(op.f('ix_experiment_assignments_experiment_id'), 'experiment_assignments', ['experiment_id'], unique=False)
    op.create_index(op.f('ix_experiment_assignments_user_id'), 'experiment_assignments', ['user_id'], unique=False)
    op.create_table('parent_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=False),
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('child_done_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['users.id'], name=op.f('fk_parent_tasks_child_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['users.id'], name=op.f('fk_parent_tasks_parent_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_parent_tasks'))
    )
    op.create_index(op.f('ix_parent_tasks_child_id'), 'parent_tasks', ['child_id'], unique=False)
    op.create_index(op.f('ix_parent_tasks_parent_id'), 'parent_tasks', ['parent_id'], unique=False)
    op.create_index(op.f('ix_parent_tasks_status'), 'parent_tasks', ['status'], unique=False)
    op.create_table('question_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('editor_id', sa.UUID(), nullable=True),
    sa.Column('change_note', sa.Text(), nullable=True),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['editor_id'], ['users.id'], name=op.f('fk_question_versions_editor_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('fk_question_versions_question_id_questions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_question_versions')),
    sa.UniqueConstraint('question_id', 'version', name='uq_question_versions_no')
    )
    op.create_index(op.f('ix_question_versions_question_id'), 'question_versions', ['question_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """降级。"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_question_versions_question_id'), table_name='question_versions')
    op.drop_table('question_versions')
    op.drop_index(op.f('ix_parent_tasks_status'), table_name='parent_tasks')
    op.drop_index(op.f('ix_parent_tasks_parent_id'), table_name='parent_tasks')
    op.drop_index(op.f('ix_parent_tasks_child_id'), table_name='parent_tasks')
    op.drop_table('parent_tasks')
    op.drop_index(op.f('ix_experiment_assignments_user_id'), table_name='experiment_assignments')
    op.drop_index(op.f('ix_experiment_assignments_experiment_id'), table_name='experiment_assignments')
    op.drop_table('experiment_assignments')
    op.drop_index(op.f('ix_inspection_reports_run_date'), table_name='inspection_reports')
    op.drop_table('inspection_reports')
    op.drop_index(op.f('ix_experiments_key'), table_name='experiments')
    op.drop_table('experiments')
    op.drop_index(op.f('ix_alert_records_kind'), table_name='alert_records')
    op.drop_table('alert_records')
    # ### end Alembic commands ###
