"""practice records

Revision ID: 72bbe0dc076a
Revises: e1071bc28a6b
Create Date: 2026-09-15 06:38:16.829786+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import pgvector  # noqa: F401  向量列（pgvector）迁移需要
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '72bbe0dc076a'
down_revision: str | None = 'e1071bc28a6b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """升级。"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('practice_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.Enum('PRACTICE', 'REPRACTICE', 'VARIANT', name='practice_source', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('user_answer', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('fk_practice_records_question_id_questions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_practice_records_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_practice_records'))
    )
    op.create_index(op.f('ix_practice_records_question_id'), 'practice_records', ['question_id'], unique=False)
    op.create_index(op.f('ix_practice_records_user_id'), 'practice_records', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """降级。"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_practice_records_user_id'), table_name='practice_records')
    op.drop_index(op.f('ix_practice_records_question_id'), table_name='practice_records')
    op.drop_table('practice_records')
    # ### end Alembic commands ###
