"""practice client event id m9

Revision ID: 8667c191a0e6
Revises: a29b14546a39
Create Date: 2026-09-16 06:13:18.242707+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import pgvector  # noqa: F401  向量列（pgvector）迁移需要
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8667c191a0e6'
down_revision: str | None = 'a29b14546a39'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """升级。"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('practice_records', sa.Column('client_event_id', sa.String(length=64), nullable=True))
    op.create_unique_constraint('uq_practice_client_event', 'practice_records', ['user_id', 'client_event_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """降级。"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_practice_client_event', 'practice_records', type_='unique')
    op.drop_column('practice_records', 'client_event_id')
    # ### end Alembic commands ###
