"""user deleted at

Revision ID: d88898187de6
Revises: 8667c191a0e6
Create Date: 2026-09-17 06:10:30.318816+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import pgvector  # noqa: F401  向量列（pgvector）迁移需要
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd88898187de6'
down_revision: str | None = '8667c191a0e6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """升级。"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """降级。"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'deleted_at')
    # ### end Alembic commands ###
