"""micro lessons

Revision ID: e1071bc28a6b
Revises: 64be57bdd33e
Create Date: 2026-09-15 06:16:26.110413+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import pgvector  # noqa: F401  向量列（pgvector）迁移需要
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e1071bc28a6b'
down_revision: str | None = '64be57bdd33e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """升级。"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('micro_lessons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('knowledge_point_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('script', sa.Text(), nullable=True),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('audio_key', sa.String(length=512), nullable=True),
    sa.Column('audio_mime', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'GENERATING', 'READY', 'FAILED', name='micro_lesson_status', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('retries', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_point_id'], ['knowledge_points.id'], name=op.f('fk_micro_lessons_knowledge_point_id_knowledge_points'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_micro_lessons_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_micro_lessons'))
    )
    op.create_index(op.f('ix_micro_lessons_knowledge_point_id'), 'micro_lessons', ['knowledge_point_id'], unique=False)
    op.create_index(op.f('ix_micro_lessons_user_id'), 'micro_lessons', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """降级。"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_micro_lessons_user_id'), table_name='micro_lessons')
    op.drop_index(op.f('ix_micro_lessons_knowledge_point_id'), table_name='micro_lessons')
    op.drop_table('micro_lessons')
    # ### end Alembic commands ###
